# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acf64856a35a5ed637aa986036a6d24267131ed0d8cdaef250314ba08966376e3fd4988da414783ab2ed9b4e8195bfce8fdb5e4483cb0afc2be387777cf94880

test:
  secret_key_base: 99f6bf46485a2a54a5fb4ec11373fdb7e1e17477e66083eb36532b4a005374a57b448366c16a79aa57957e8b52384615a3faa0be7fceaf6b4b7a077fc95a5a28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
